spring.application.name=demoMVCCRUD



#We manually add 'jdbc:' before the variable
spring.datasource.url=jdbc:${MYSQL_URL}

#we reference the password and username
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# 3. CRITICAL FIX: Do not use MYSQLPORT here!
# Railway assigns a specific HTTP port for your app in a variable simply called PORT.
server.port=${PORT:8080}