spring.application.name=demoMVCCRUD




spring.datasource.url=${{MySQL.MYSQL_URL}}
spring.datasource.username=${{MySQL.MYSQLUSER}}
spring.datasource.password=${{MySQL.MYSQLPASSWORD}}
server.port=${{MySQL.MYSQLPORT}}
