#These properties are for local testing only

#We manually add 'jdbc:' before the variable
spring.datasource.url=jdbc:mysql://localhost:3306/customer_tracker

#we reference the password and username
spring.datasource.username=springstudent
spring.datasource.password=springstudent


# Railway assigns a specific HTTP port for your app in a variable simply called PORT.
server.port=${PORT:8080}